import { Fragment, useEffect } from 'react'
import '../styles/globals.css'
import Head from 'next/head'
import AOS from "aos";
import "aos/dist/aos.css";

function MyApp({ Component, pageProps }) {

  useEffect(()=>{
        AOS.init({
          startEvent: 'DOMContentLoaded',  
        });
  },[])

  return (
    <Fragment>
      <Head>
        <title>Nusantara Siber Integrasi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.webp" />
      </Head>
      <Component {...pageProps} />
    </Fragment>
  )
}

export default MyApp
